import 'package:cero_a_experto/domain/datasources/movies_datasource.dart';
import 'package:cero_a_experto/domain/entities/movie.dart';
import 'package:cero_a_experto/infrastructure/mappers/movie_mapper.dart';
import 'package:cero_a_experto/infrastructure/models/moviedb/movie_db_response.dart';

const data = {
  "dates": {"maximum": "2026-06-24", "minimum": "2026-05-13"},
  "page": 1,
  "results": [
    {
      "adult": false,
      "backdrop_path": "/5lTZyuBTNOfawsfPT8Q0cIg6qAF.jpg",
      "genre_ids": [27, 53],
      "id": 1339713,
      "title": "Obsession",
      "original_language": "en",
      "original_title": "Obsession",
      "overview":
          "After breaking the mysterious \"One Wish Willow\" to win his crush's heart, a hopeless romantic finds himself getting exactly what he asked for but soon discovers that some desires come at a dark, sinister price.",
      "popularity": 617.3077,
      "poster_path": "/bRwnj8WEKBCvmfeUNOukJPwB43K.jpg",
      "release_date": "2026-05-13",
      "softcore": false,
      "video": false,
      "vote_average": 7.913,
      "vote_count": 817,
    },
    {
      "adult": false,
      "backdrop_path": "/laR2dpcNpbv83jdlRUNAYPPjH90.jpg",
      "genre_ids": [28, 14, 12],
      "id": 931285,
      "title": "Mortal Kombat II",
      "original_language": "en",
      "original_title": "Mortal Kombat II",
      "overview":
          "The fan favorite champions—now joined by Johnny Cage himself—are pitted against one another in the ultimate, no-holds barred, gory battle to defeat the dark rule of Shao Kahn that threatens the very existence of the Earthrealm and its defenders.",
      "popularity": 536.6859,
      "poster_path": "/hwRdDFIhaEmpRgoki805YvyyjZf.jpg",
      "release_date": "2026-05-06",
      "softcore": false,
      "video": false,
      "vote_average": 7.988,
      "vote_count": 1426,
    },
    {
      "adult": false,
      "backdrop_path": "/ufSwlnECLoUbBjPrFqEQcWBzHwc.jpg",
      "genre_ids": [10402, 18],
      "id": 936075,
      "title": "Michael",
      "original_language": "en",
      "original_title": "Michael",
      "overview":
          "The story of Michael Jackson, one of the most influential artists the world has ever known, and his life beyond the music. His journey from the discovery of his extraordinary talent as the lead of the Jackson Five, to the visionary artist whose creative ambition fueled a relentless pursuit to become the biggest entertainer in the world, highlighting both his life off-stage and some of the most iconic performances from his early solo career.",
      "popularity": 512.4438,
      "poster_path": "/zm0KAbOjlt9eR5y7vDiL2dEOwMl.jpg",
      "release_date": "2026-04-22",
      "softcore": false,
      "video": false,
      "vote_average": 8.649,
      "vote_count": 2565,
    },
    {
      "adult": false,
      "backdrop_path": "/oPsRr7AfNLw6XaPuMpvkWK0bIUA.jpg",
      "genre_ids": [28, 18],
      "id": 1057265,
      "title": "Peddi",
      "original_language": "te",
      "original_title": "పెద్ది",
      "overview":
          "In 1980s rural Andhra Pradesh, a spirited villager unites his community through sports to defend their pride against a powerful rival.",
      "popularity": 361.9352,
      "poster_path": "/kJAJNNBYlbqAcpTDxBNnaILSMTy.jpg",
      "release_date": "2026-06-03",
      "softcore": false,
      "video": false,
      "vote_average": 6.547,
      "vote_count": 43,
    },
    {
      "adult": false,
      "backdrop_path": "/1eAuwNBy34kkM3xkl202z4f1NiI.jpg",
      "genre_ids": [28, 14],
      "id": 1367220,
      "title": "Karuppu",
      "original_language": "ta",
      "original_title": "கருப்பு",
      "overview":
          "In a world where justice falters, guardian deity Vettai Karuppu takes the guise of a lawyer to battle a corrupt legal system preying on the powerless.",
      "popularity": 413.7865,
      "poster_path": "/4KZXlZ5tTT6ghbW77gS4hSLkCd7.jpg",
      "release_date": "2026-05-14",
      "softcore": false,
      "video": false,
      "vote_average": 7.059,
      "vote_count": 17,
    },
    {
      "adult": false,
      "backdrop_path": "/l5QgEvlfK6eHPM4YPEk7AArXmh8.jpg",
      "genre_ids": [10749, 35],
      "id": 1308553,
      "title": "Hai Jawani Toh Ishq Hona Hai",
      "original_language": "hi",
      "original_title": "है जवानी तो इश्क होना है",
      "overview":
          "When Jass leaves his marriage over conflicting priorities, a new romance abroad is upended by shocking revelations, forcing him to confront love, loyalty, and the true meaning of commitment.",
      "popularity": 289.6886,
      "poster_path": "/vmlJvz6qVzYgei2V74GvnmcuQfW.jpg",
      "release_date": "2026-06-04",
      "softcore": false,
      "video": false,
      "vote_average": 5.471,
      "vote_count": 17,
    },
    {
      "adult": false,
      "backdrop_path": "/s6ly8laenkHWlIBRkLSfIuEMLC6.jpg",
      "genre_ids": [53, 878, 9648],
      "id": 1275779,
      "title": "Disclosure Day",
      "original_language": "en",
      "original_title": "Disclosure Day",
      "overview":
          "If you found out we weren’t alone, if someone showed you, proved it to you, would that frighten you?",
      "popularity": 326.4035,
      "poster_path": "/3o5YPjDGDTcTDL5ftDA9NwN9dLd.jpg",
      "release_date": "2026-06-10",
      "softcore": false,
      "video": false,
      "vote_average": 6.8,
      "vote_count": 480,
    },
    {
      "adult": false,
      "backdrop_path": "/A2tzVTVtnTvpji96IZmleN78KKv.jpg",
      "genre_ids": [27, 35],
      "id": 1239134,
      "title": "Bhooth Bangla",
      "original_language": "hi",
      "original_title": "भूत बंगला",
      "overview":
          "A man inherits a palace in rural Mangalpur and plans his sister's wedding there, but strange supernatural events and panicked locals force him to investigate the property's mysterious past.",
      "popularity": 337.3635,
      "poster_path": "/79RBp8afL4u4z3nVGR78z6eIvBB.jpg",
      "release_date": "2026-04-16",
      "softcore": false,
      "video": false,
      "vote_average": 5.5,
      "vote_count": 20,
    },
    {
      "adult": false,
      "backdrop_path": "/6zg7A9ICOthNR2TSXlT51KvXrsA.jpg",
      "genre_ids": [28, 12, 878],
      "id": 1228710,
      "title": "The Mandalorian and Grogu",
      "original_language": "en",
      "original_title": "The Mandalorian and Grogu",
      "overview":
          "The evil Empire has fallen, and Imperial warlords remain scattered throughout the galaxy. As the fledgling New Republic works to protect everything the Rebellion fought for, they have enlisted the help of legendary Mandalorian bounty hunter Din Djarin and his young apprentice Grogu.",
      "popularity": 239.2479,
      "poster_path": "/5Vi8dSauVwH1HOsiZceDMbRr1Ca.jpg",
      "release_date": "2026-05-20",
      "softcore": false,
      "video": false,
      "vote_average": 6.766,
      "vote_count": 481,
    },
    {
      "adult": false,
      "backdrop_path": "/xugEpZk9YQ0DIz1aFvH5HGkqpZK.jpg",
      "genre_ids": [27, 9648],
      "id": 1304313,
      "title": "Lee Cronin's The Mummy",
      "original_language": "en",
      "original_title": "Lee Cronin's The Mummy",
      "overview":
          "The young daughter of a journalist disappears into the desert without a trace—eight years later, the broken family is shocked when she is returned to them, as what should be a joyful reunion turns into a living nightmare.",
      "popularity": 168.1853,
      "poster_path": "/1q308iixueCU4pFtSYugNOevtNx.jpg",
      "release_date": "2026-04-15",
      "softcore": false,
      "video": false,
      "vote_average": 8.048,
      "vote_count": 1860,
    },
    {
      "adult": false,
      "backdrop_path": "/piV2OnzTZCyGBP9JCjlHIgKGlfo.jpg",
      "genre_ids": [28, 14, 878],
      "id": 454639,
      "title": "Masters of the Universe",
      "original_language": "en",
      "original_title": "Masters of the Universe",
      "overview":
          "After being separated for 15 years, the Sword of Power leads Prince Adam back to Eternia, where he discovers his home shattered under the fiendish rule of Skeletor. To save his family and his world, Adam must join forces with his closest allies, Teela and Duncan/Man-At-Arms, and embrace his true destiny as He-Man — the most powerful man in the universe.",
      "popularity": 152.4585,
      "poster_path": "/3YMd9Ogae4rDKLWuAZFuse9xhc5.jpg",
      "release_date": "2026-06-03",
      "softcore": false,
      "video": false,
      "vote_average": 7.269,
      "vote_count": 236,
    },
    {
      "adult": false,
      "backdrop_path": "/ew3EqF9VLTxmK64OsHT7p7lr4wT.jpg",
      "genre_ids": [28, 80],
      "id": 1280738,
      "title": "The Furious",
      "original_language": "en",
      "original_title": "火遮眼",
      "overview":
          "After Wang Wei's daughter is kidnapped by a criminal network and he receives no help from the corrupt police, Wei sets out to find her himself. His only ally is Navin, a relentless journalist whose wife has mysteriously disappeared. Fueled by a furious vengeance, the unlikely duo ruthlessly battle the kidnappers in this explosive martial arts showdown.",
      "popularity": 173.2088,
      "poster_path": "/zP19YO60jwEsfKd5Qf1UvA5uJu8.jpg",
      "release_date": "2026-06-10",
      "softcore": false,
      "video": false,
      "vote_average": 8.1,
      "vote_count": 39,
    },
    {
      "adult": false,
      "backdrop_path": "/kwq3lxPrBfyyVRRSDSlojwCPzwH.jpg",
      "genre_ids": [16, 10751, 35, 12],
      "id": 1084244,
      "title": "Toy Story 5",
      "original_language": "en",
      "original_title": "Toy Story 5",
      "overview":
          "When Bonnie receives a Lilypad tablet as a gift and becomes obsessed, Buzz, Woody, Jessie and the rest of the gang's jobs become exponentially harder when they have to go head to head with the all-new threat to playtime.",
      "popularity": 159.9439,
      "poster_path": "/pxG26JdyuiDvJbSoucknaFiLeZD.jpg",
      "release_date": "2026-06-17",
      "softcore": false,
      "video": false,
      "vote_average": 7.0,
      "vote_count": 33,
    },
    {
      "adult": false,
      "backdrop_path": "/xS8tsJ8IvNkzBMu3kq3gZFReh7j.jpg",
      "genre_ids": [53],
      "id": 1293550,
      "title": "Bandar",
      "original_language": "hi",
      "original_title": "बंदर",
      "overview":
          "TV star Samar's life spirals when his ex Gayatri accuses him of rape after he blocks contact with her. Despite his new relationship with Khushi, he faces arrest and encounters a corrupt justice system.",
      "popularity": 138.9755,
      "poster_path": "/3TrQUHmnEL2tOYf4KKkXb01BQt2.jpg",
      "release_date": "2026-06-05",
      "softcore": false,
      "video": false,
      "vote_average": 7.0,
      "vote_count": 1,
    },
    {
      "adult": false,
      "backdrop_path": "/qcIKxhqGMIj8uujsSoSMZWr8QqU.jpg",
      "genre_ids": [28, 53],
      "id": 1122573,
      "title": "In the Grey",
      "original_language": "en",
      "original_title": "In the Grey",
      "overview":
          "A covert team of elite operatives are living in the shadows. When a ruthless despot steals a billion-dollar fortune, they're sent to take it back—an impossible heist that erupts into a deadly game of strategy, deception and survival.",
      "popularity": 144.0062,
      "poster_path": "/dQgIcW6Th08kMRf2HBoYWoFE6OD.jpg",
      "release_date": "2026-05-13",
      "softcore": false,
      "video": false,
      "vote_average": 6.62,
      "vote_count": 238,
    },
    {
      "adult": false,
      "backdrop_path": "/gRoZG3Z0zJxgElmTsVHOl2dNYXe.jpg",
      "genre_ids": [28, 80, 53],
      "id": 1582770,
      "title": "Dhurandhar: The Revenge",
      "original_language": "hi",
      "original_title": "धुरंधर: द रिवेंज",
      "overview":
          "As rival gangs, corrupt officials and a ruthless Major Iqbal close in, Hamza's mission for his country spirals into a bloody personal war where the line between patriot and monster disappears in the streets of Lyari.",
      "popularity": 133.8815,
      "poster_path": "/ptTwQES14pr5c3aZvJg56YlYgb1.jpg",
      "release_date": "2026-03-18",
      "softcore": false,
      "video": false,
      "vote_average": 7.3,
      "vote_count": 119,
    },
    {
      "adult": false,
      "backdrop_path": "/1N5yz1IDw6Ci8le1YgeM6xtBijA.jpg",
      "genre_ids": [10749, 35],
      "id": 1358005,
      "title": "Office Romance",
      "original_language": "en",
      "original_title": "Office Romance",
      "overview":
          "Jackie, President and CEO of Air Cruz, runs a tight ship in her business, including a rigid anti-fraternization policy for all her employees. When a new sexy lawyer begins working for her, that policy becomes very tested.",
      "popularity": 121.7414,
      "poster_path": "/1HRUTqEVDmJC4L6tp6zd85MI6uH.jpg",
      "release_date": "2026-06-04",
      "softcore": false,
      "video": false,
      "vote_average": 6.5,
      "vote_count": 209,
    },
    {
      "adult": false,
      "backdrop_path": "/dd31qJxOarrHyGZwYsCzOjobQzP.jpg",
      "genre_ids": [28, 53],
      "id": 1380291,
      "title": "Tom Clancy's Jack Ryan: Ghost War",
      "original_language": "en",
      "original_title": "Tom Clancy's Jack Ryan: Ghost War",
      "overview":
          "Jack Ryan is reluctantly pulled back into espionage when an international covert mission unravels a deadly conspiracy. Racing against time, he joins CIA allies Mike November & James Greer and sharp MI6 officer Emma Marlowe to battle a rogue black-ops unit in a high-stakes, deeply personal fight.",
      "popularity": 115.9087,
      "poster_path": "/8ehYxUh5MWE41AeE9gkHE8DKzvB.jpg",
      "release_date": "2026-05-20",
      "softcore": false,
      "video": false,
      "vote_average": 7.076,
      "vote_count": 575,
    },
    {
      "adult": false,
      "backdrop_path": "/wQOhbCP6H8bO5ddlXDZT207orew.jpg",
      "genre_ids": [10749, 18],
      "id": 1477317,
      "title": "Your Fault: London",
      "original_language": "en",
      "original_title": "Your Fault: London",
      "overview":
          "Nick and Noah are both embarking on life-changing adventures that are threatening to pull them apart—Nick in business with his father and Noah starting a fresh chapter at Oxford University. Now living separate lives, and meeting new people, they find themselves entangled in temptations, rivalries, and betrayals and their bond is tested like never before. As secrets unravel and temptation rises, they must fight to hold onto each other—or risk losing everything.",
      "popularity": 115.1238,
      "poster_path": "/nLxu237EJAisFCYKK48hN9Plobx.jpg",
      "release_date": "2026-06-17",
      "softcore": false,
      "video": false,
      "vote_average": 7.824,
      "vote_count": 37,
    },
    {
      "adult": false,
      "backdrop_path": "/mCpwRayjXMFzKHbjbzc5JRKfq1O.jpg",
      "genre_ids": [27, 9648, 878],
      "id": 1083381,
      "title": "Backrooms",
      "original_language": "en",
      "original_title": "Backrooms",
      "overview": "A strange doorway appears in the basement of a furniture showroom.",
      "popularity": 114.9773,
      "poster_path": "/rhGx6E3qRNMgj3i5su2oukNHwIQ.jpg",
      "release_date": "2026-05-27",
      "softcore": false,
      "video": false,
      "vote_average": 6.891,
      "vote_count": 586,
    },
  ],
  "total_pages": 292,
  "total_results": 5824,
};

class MovieDbOfflineDatasource extends MoviesDatasource {
  @override
  Future<List<Movie>> getNowPlaying({int page = 1, String language = 'en-US'}) async {
    final List<Movie> movies = [
      ...MovieDbResponse.fromJson(data).results.map((m) => MovieMapper.movieDBToEntity(m)),
    ];

    return movies;
  }
}
